spring.application.name=backend
spring.datasource.url=${spring.datasource.url}
spring.datasource.username=${spring.datasource.username}
spring.datasource.password=${spring.datasource.password}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.ddl-auto=update
hibernate.hbm2ddl.auto=update
spring.servlet.multipart.max-file-size =-1
spring.servlet.multipart.max-request-size =-1
server.port=8080
config.mail.smtp=${config.mail.smtp}
config.mail.port=${config.mail.port}
config.mail.address=${config.mail.address}
config.mail.token=${config.mail.token}
app.upload.dir=uploads